# Makefile for C Collections Project

CC = gcc
# Installation prefix and staging
PREFIX ?= /usr/local
DESTDIR ?=

# Flags
CPPFLAGS += -Iinclude -fsanitize=address
CFLAGS = -std=c2x -Wall -Wextra
DEPFLAGS = -MMD -MP
PICFLAGS = -fPIC
LDFLAGS += -fsanitize=address
AR = ar
ARFLAGS = rcs

# Utilities
RM := rm -rf
INSTALL := install
INSTALL_DATA := $(INSTALL) -m 644
INSTALL_PROG := $(INSTALL) -m 755

# Directories
SRC_DIR = src
INC_DIR = include
TST_SRC_DIR = test
BLD_DIR = build
LIB_DIR = lib
API_DOC_DIR = apidoc

# Library names
STATIC_LIB = $(LIB_DIR)/libcollections.a
SHARED_LIB = $(LIB_DIR)/libcollections.so

# Sources are placed in subdirs of $(SRC_DIR)
# See https://www.gnu.org/software/make/manual/html_node/Wildcard-Function.html
SOURCES := $(wildcard $(SRC_DIR)/*/*.c)

# Library objects go into $(BLD_DIR)/lib/ preserving subdirs
LIB_OBJ := $(patsubst $(SRC_DIR)/%.c,$(BLD_DIR)/lib/%.o,$(SOURCES))

# Test sources discovery and objects under $(BLD_DIR)/test/
TST_SRC := $(wildcard $(TST_SRC_DIR)/*.c) $(wildcard $(TST_SRC_DIR)/*/*.c)
TST_OBJ := $(patsubst $(TST_SRC_DIR)/%.c,$(BLD_DIR)/test/%.o,$(TST_SRC))

# Object files (tests + library objects)
ALL_OBJ = $(TST_OBJ) $(LIB_OBJ)

# Include dependency files generated by the compiler (ignore missing files)
-include $(ALL_OBJ:.o=.d)

# Executables
TEST_EXE = $(BLD_DIR)/unittest

# Default target
all: test

# Ensure directories exist
$(BLD_DIR):
	mkdir -p $(BLD_DIR)

$(LIB_DIR):
	mkdir -p $(LIB_DIR)

# Build the test executable
$(TEST_EXE): $(ALL_OBJ)
	$(CC) $(LDFLAGS) -o $@ $(ALL_OBJ)

# Generic rule: compile test source files from $(TST_SRC_DIR) into matching objects under $(BLD_DIR)/test/
$(BLD_DIR)/test/%.o: $(TST_SRC_DIR)/%.c | $(BLD_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

# Generic rule: compile library source files from $(SRC_DIR) into matching objects under $(BLD_DIR)/lib/
$(BLD_DIR)/lib/%.o: $(SRC_DIR)/%.c | $(BLD_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PICFLAGS) $(DEPFLAGS) -c $< -o $@

# Static library
$(STATIC_LIB): $(LIB_OBJ) | $(LIB_DIR)
	@mkdir -p $(dir $@)
	$(AR) $(ARFLAGS) $@ $^

# Shared library
$(SHARED_LIB): $(LIB_OBJ) | $(LIB_DIR)
	@mkdir -p $(dir $@)
	$(CC) -shared -o $@ $^ $(LDFLAGS)

# Convenience targets to build libraries
libs: $(STATIC_LIB) $(SHARED_LIB)

static: $(STATIC_LIB)

shared: $(SHARED_LIB)

# Run tests
test: $(TEST_EXE)
	./$(TEST_EXE)

# Clean build artifacts
clean:
	$(RM) $(BLD_DIR)
	$(RM) $(STATIC_LIB) $(SHARED_LIB)
	$(RM) $(API_DOC_DIR)

# Install headers
install-headers:
	mkdir -p $(DESTDIR)$(PREFIX)/include/collections
	$(INSTALL_DATA) include/*.h $(DESTDIR)$(PREFIX)/include/collections/

# Install static library
install-static: $(STATIC_LIB)
	mkdir -p $(DESTDIR)$(PREFIX)/lib
	$(INSTALL_DATA) $(STATIC_LIB) $(DESTDIR)$(PREFIX)/lib/

# Install shared library
install-shared: $(SHARED_LIB)
	mkdir -p $(DESTDIR)$(PREFIX)/lib
	$(INSTALL_PROG) $(SHARED_LIB) $(DESTDIR)$(PREFIX)/lib/

# Install both libraries and headers
install: install-static install-shared install-headers

# Generate documentation (placeholder)
apidoc: 
	doxygen Doxyfile

# Phony targets
.PHONY: all test clean libs static shared install install-static install-shared install-headers apidoc

